# Generated by Django 2.2.5 on 2020-02-12 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(max_length=64, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Name contains not allowed characters!', regex='[\\[@!#$%^&*()<>?/\\|}{~:\\] ]')]),
        ),
        migrations.AlterField(
            model_name='source',
            name='component_id',
            field=models.CharField(help_text='The ID of the component from which the source comes from', max_length=64),
        ),
        migrations.AlterField(
            model_name='source',
            name='island_id',
            field=models.CharField(help_text='The ID of the island from which the source comes from', max_length=64),
        ),
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
