# Generated by Django 3.0.3 on 2020-03-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_q3c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='ave_flux_int',
            new_name='avg_flux_int',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='ave_flux_peak',
            new_name='avg_flux_peak',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='ave_dec',
            new_name='wavg_dec',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='ave_ra',
            new_name='wavg_ra',
        ),
        migrations.AddField(
            model_name='measurement',
            name='error_radius',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='ew_sys_err',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='ns_sys_err',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='uncertainty_ew',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='uncertainty_ns',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='wavg_uncertainty_ew',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='source',
            name='wavg_uncertainty_ns',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
