name: 'create-dev-database'
description: 'Create a database for VAST development'

inputs:
  db_password:
    description: 'Database password'
    required: false
    default: 'postgres'
  db_port:
    description: 'Database port'
    required: false
    default: '5432'

runs:
  using: "composite"
  steps:
    - run: docker-compose up -d
      working-directory: ${{ github.action_path }}
      shell: bash
      env:
        DB_PORT: ${{ inputs.db_port }}
        DB_PASSWORD: ${{ inputs.db_password }}
