version: "3"

services:

  database:
    image: ghcr.io/marxide/postgres-q3c:latest
    container_name: vast-dev-db
    ports:
      - "127.0.0.1:${DB_PORT}:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
