# Generated by Django 5.1.5 on 2025-01-30 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vast_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            ["CREATE EXTENSION IF NOT EXISTS q3c;"],#upgrade
            ["DROP EXTENSION IF EXISTS q3c;"],#downgrade
        ),
    ]
