# Generated by Django 5.1.6 on 2025-03-30 23:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vast_pipeline', '0002_q3c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
