# Generated by Django 3.0.7 on 2020-10-16 21:39

from django.db import migrations, models
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('vast_pipeline', '0002_q3c'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagulous_Source_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name='source',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, autocomplete_settings={'width': '100%'}, autocomplete_view='vast_pipeline:source_tags_autocomplete', help_text='Enter a comma-separated tag string', space_delimiter=False, to='vast_pipeline.Tagulous_Source_tags'),
        ),
    ]
