# Generated by Django 3.2.2 on 2021-05-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vast_pipeline', '0003_auto_20210402_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveysource',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='source',
            name='cross_match_sources',
        ),
        migrations.DeleteModel(
            name='CrossMatch',
        ),
        migrations.DeleteModel(
            name='Survey',
        ),
        migrations.DeleteModel(
            name='SurveySource',
        ),
    ]
