# Generated by Django 3.2.2 on 2021-05-21 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vast_pipeline', '0004_auto_20210521_1339'),
        ('vast_pipeline', '0004_source_name_change'),
    ]

    operations = [
    ]
