# Generated by Django 3.2.2 on 2021-09-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vast_pipeline', '0005_merge_0004_auto_20210521_1339_0004_source_name_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='run',
            name='status',
            field=models.CharField(choices=[('INI', 'Initialised'), ('QUE', 'Queued'), ('RUN', 'Running'), ('END', 'Completed'), ('ERR', 'Error'), ('RES', 'Restoring'), ('DEL', 'Deleting')], default='INI', help_text='Status of the pipeline run.', max_length=3),
        ),
    ]
