# Generated by Django 3.2.2 on 2021-10-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vast_pipeline', '0006_alter_run_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
