# Generated by Django 3.2.13 on 2023-01-25 18:13

from django.db import migrations, models, transaction


class Migration(migrations.Migration):

    dependencies = [
        ('vast_pipeline', '0010_update_source_names_iau_compliant'),
    ]

    def fill_new_source_counts(apps, schema_editor):
        """Loop over Run objects and count the number of new sources and save to new column."""
        Run = apps.get_model("vast_pipeline", "Run")
        Source = apps.get_model("vast_pipeline", "Source")

        runs = Run.objects.all()

        for run in runs:
            with transaction.atomic():
                n_new_sources = Source.objects.filter(run=run, new=True).count()
                run.n_new_sources = n_new_sources
                run.save()

    operations = [
        migrations.AddField(
            model_name='run',
            name='n_new_sources',
            field=models.IntegerField(default=0, help_text='number of new sources in this run'),
        ),
        migrations.RunPython(fill_new_source_counts, atomic=False)
    ]
