# Generated by Django 3.2.25 on 2025-05-05 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vast_pipeline', '0011_run_n_new_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageCutout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cutouts/')),
                ('size', models.CharField(choices=[('normal', 'Normal'), ('large', 'Large'), ('xlarge', 'XLarge')], max_length=10)),
                ('img_type', models.CharField(choices=[('fits', 'FITS'), ('png', 'PNG')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutouts', to='vast_pipeline.measurement')),
            ],
            options={
                'unique_together': {('measurement', 'size', 'img_type')},
            },
        ),
    ]
