name: ci docs

# a merged PR will trigger a push on master so merging to master is
# included in the event below
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.fork == false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: Gr1N/setup-poetry@v4
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libpq-dev libgraphviz-dev
      - name: Cache Python dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry/virtualenvs
          key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
      - name: Install python dependencies
        run: poetry install
      - name: Build and deploy docs
        run: poetry run mkdocs gh-deploy -m 'github action deployment' --force
