name: lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        use-pylint: false
        use-pycodestyle: false
        use-flake8: true
        use-black: false
        use-mypy: false
        use-isort: false
        extra-pylint-options: ""
        extra-pycodestyle-options: ""
        extra-flake8-options: "--select=W291,W292,F401"
        # flake8 options being used:
        #   - W291 trailing whitespace
        #   - W292 no newline at end of file
        #   - F401 module imported but unused
        extra-black-options: ""
        extra-mypy-options: ""
        extra-isort-options: ""
